name: final_project
description: "A new Flutter project."
publish_to: 'none' # Prevents publishing to pub.dev
version: 1.0.0+1  # Version: major.minor+build

environment:
  sdk: ^3.7.0 # Specifies the Dart SDK version to use

dependencies:
  flutter:
    sdk: flutter  # Main Flutter SDK
  cupertino_icons: ^1.0.8 # iOS-style icons
  firebase_core: ^2.27.0 # Required to initialize Firebase
  firebase_auth: ^4.17.0 # Firebase Authentication
  cloud_firestore: ^4.15.0 # Cloud Firestore for storing tasks
  intl: ^0.18.1 # Date formatting and internationalization
  table_calendar: ^3.0.9  # Calendar widget for selecting dates

dev_dependencies:
  flutter_test:
    sdk: flutter  # For running Flutter tests
  flutter_lints: ^3.0.1 # Recommended linter rules

flutter:
  uses-material-design: true # Enables Material Design icons
  assets:
    - images/red_deer_logo.png # Path to the logo image used in AppBar
