// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQbkZn7ncs1iL2qH_nW-Y-vLbxXBq0-rE',
    appId: '1:69425150349:web:a5fcc981106bd4e902e5c4',
    messagingSenderId: '69425150349',
    projectId: 'hrn-flutter',
    authDomain: 'hrn-flutter.firebaseapp.com',
    storageBucket: 'hrn-flutter.firebasestorage.app',
    measurementId: 'G-PD2N9R626G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9WnkvWEVdSNbjgwEqTfL5HY-vTCnBrYQ',
    appId: '1:69425150349:android:f7492573767faffd02e5c4',
    messagingSenderId: '69425150349',
    projectId: 'hrn-flutter',
    storageBucket: 'hrn-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAo8pTig9vbKlDxjaZ2VtI8DTZniaIjxs',
    appId: '1:69425150349:ios:4da4f90e6c8a03fc02e5c4',
    messagingSenderId: '69425150349',
    projectId: 'hrn-flutter',
    storageBucket: 'hrn-flutter.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAo8pTig9vbKlDxjaZ2VtI8DTZniaIjxs',
    appId: '1:69425150349:ios:4da4f90e6c8a03fc02e5c4',
    messagingSenderId: '69425150349',
    projectId: 'hrn-flutter',
    storageBucket: 'hrn-flutter.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQbkZn7ncs1iL2qH_nW-Y-vLbxXBq0-rE',
    appId: '1:69425150349:web:11c1cc8853335d6402e5c4',
    messagingSenderId: '69425150349',
    projectId: 'hrn-flutter',
    authDomain: 'hrn-flutter.firebaseapp.com',
    storageBucket: 'hrn-flutter.firebasestorage.app',
    measurementId: 'G-BJB23R9V12',
  );
}
